### ISSUE TITLE
Feature request: Optional API keys per assistant

### ISSUE THREAD

**Issue by PatrickJongmans** [santthosh/assistants-hub#81]
Add option to add custom API keys per assistant.

**Comment by santthosh** [comment]
@PatrickJongmans - good call out, will try to fix this for the next release

**Comment by santthosh** [comment]
This is now completed @PatrickJongmans! You can now manage API credentials globally also have 1 API key per assistant. Please try out and let me know


https://github.com/assistants-hub/assistantshub.ai/assets/2665127/d648fbc7-4808-4570-ad58-a94ed8c8d0c3
